---
abstract: 'Access Etherpad Lite API easily'
author:
  - 'Luc DIDRY (ldidry@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Etherpad-API
no_index:
  directory:
    - t
    - inc
requires:
  JSON::XS: 0
  LWP::UserAgent: 0
  Test::Simple: 0.44
resources:
  repository: git://github.com/ldidry/etherpad-api.git
version: 0.08
