---
abstract: 'Access Etherpad Lite API easily'
author:
  - 'Luc DIDRY (ldidry@cpan.org)'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Etherpad-API
no_index:
  directory:
    - t
    - inc
resources:
  repository: git://github.com/ldidry/etherpad-api.git
version: 0.11
